modLoader = "kotlinforforge"
loaderVersion = "[4.11,)"
license = "MIT License"
logoFile="kotlinscript.png"

[[mods]]
    modId = "kotlinscript"
    version = "1.4"
    displayName = "KotlinScript For Forge"
    displayURL = "https://github.com/HollowHorizon/"
    authors = "HolloHorizon"
    credits = "KitoWasHere by porting to 1.20.1"
    description = '''
    Mod that provides tools for compiling kotlin scripts at runtime.
    '''
[[dependencies.kotlinscript]]
    modId = "forge"
    mandatory = true
    versionRange = "[46,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kotlinscript]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.kotlinscript]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="[4.11,)"
    ordering = "AFTER"
    side = "BOTH"
