modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "MIT License"
[[mods]]
modId = "kotlinscript"
version = "1.0"
displayName = "KotlinScript For Forge"
displayURL = "https://github.com/HollowHorizon/"
authors = "HolloHorizon"
description = '''
Mod that provides tools for compiling kotlin scripts at runtime.
'''
[[dependencies.kotlinscript]]
modId = "forge"
mandatory = true
versionRange = "[40,44.0.0)"
ordering = "NONE"
side = "BOTH"
[[dependencies.kotlinscript]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.kotlinscript]]
modId="hc"
mandatory=true
versionRange="[1.3.2,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.kotlinscript]]
modId="kotlinforforge"
mandatory=true
versionRange="[3.10.0,)"
ordering = "AFTER"
side = "BOTH"
